pipeline {
  agent any

  stages {
    stage('checkout'){
      steps{
        echo 'build started'
           checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkins-git', url: 'https://github.com/anirudhnikhils/ci-cd--Spring.git']])
        echo'build completed'
      }
    }
  
  stage('maven build'){
    steps{
      echo'maven build started'
      dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app'){
        sh 'mvn clean package'
}
    }
  }
  }
}
    
