pipeline {
  agent any
	tools{
		maven 'Maven 3.x' // The name you provided in the Global Tool Configuration
	}

  stages {
    stage('checkout'){
      steps{
        echo 'build started'
           checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkins-git', url: 'https://github.com/anirudhnikhils/ci-cd--Spring.git']])
        echo'build completed'
      }
    }
  
  stage('maven build'){
    steps{
    echo'maven build started'
	bat 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
	echo 'maven build completed'
    }
  }
  stage('mvn test'){
  steps{
    echo 'mvn test start'
	bat 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn test'
	echo 'maven test completed'
	}
  }
  stage('dcker build and push'){
    enviroment{
	docker_image = "anirudhnikhil/spring:${BUILD_NUMBER}"
	 REGISTRY_CREDENTIALS = credentials('docker_cred')
	}
	steps{
	    script{
	         bat 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && docker build -t ${docker_image}'
	         dockerImage = docker.image("${docker_image}")
	         docker.withRegistry('https://index.docker.io/v1/', "docker_cred"){
	         dockerImage.push()
			 }
			}
	}
	
  }
}
