pipeline {
  agent any

  stages {
    stage('checkout'){
      steps{
        
        checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkins-git', url: 'https://github.com/anirudhnikhils/ci-cd--Spring.git']])
      }
    }
  }
}
